https://invent.kde.org/sdk/umbrello/-/merge_requests/50 umbrello/models/stereotypesmodel.h : Replace forward declaration of UMLStereotype by #include "stereotype.h"
in preparation of switch to Qt6 where Q_DECLARE_METATYPE(UMLStereotype*)
requires the full type to be visible, otherwise there is compile error
> /usr/include/qt6/QtCore/qmetatype.h:1189:55: error: static assertion
> failed: Pointer Meta Types must either point to fully-defined types
> or be declared with Q_DECLARE_OPAQUE_POINTER(T *)